Feat display suspension list
pebble-solutions/App-QSE-habilitation pull request #72
Opened 2023-09-19 17:54 UTC by deathtroll22

ne pas supprimer cette branche après le merge. ou bien verifier que la liste du personnel dans le fils a le meme CSS

2023-09-19 18:04 UTC, deathtroll22 commented
la modale avec les possibilités de suppression de suspension et modification de df viendront dans une prochaine iteration de l'app. :)

2023-09-21 08:36 UTC, Guillaume35 requested changes

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/Suspension.vue
> +.card {
Il existe une classe Bootstrap pour supprimer les bordures :

`border-0`

Appliquer cette classe sur les éléments viser plutôt que de ré-écrire la classe .card .

De manière générale, NE PAS ré-écrire les propriétés des classes bootstrap. Créer de nouveaux noms de classe. Les noms de classes doivent être claire afin de pouvoir être comprises par d'autres développeurs.

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/Suspension.vue
> +.bg-custom {
Il y a une erreur dans le nom de la couleur. 9a en trop à la fin.
De plus, ces classes devraient se trouver dans App.vue ou dans un fichier css général appelé partout.

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/SuspensionsPersonnelInformations.vue
> +        getNonSuspendedHabilitations() {
Le propriété computed ne sont pas des getters. La méthode devrait être `nonSuspendedHabilitations()`

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/SuspensionsPersonnelInformations.vue
> +        getSuspendedHabilitations() {
Idem à commentaire précédent

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/SuspensionsPersonnelInformations.vue
> +        getHabilitationTypeName() {
Cette méthode ne peut pas fonctionner :

- La méthode est déclarée dans `computed`, elle doit être déclarée dans `methods`.
- La description de la méthode indique qu'elle accepte un paramètre. Hors elle n'en accepte aucun
- `habilitationTypeId` est forcément null puisque la variable n'est pas fournis dans l'entête de la fonction
- La fonction doit retourner une valeur (`string`), ici elle retourne une autre fonction anonyme.

Résolution :
- Déclarer la fonction de methods
- Modifier l'entête de fonction et sa logique :

```JavaScript
getHabilitationTypeName(habilitationTypeId) {
    const habilitationType = this.types.find(type => type.id === habilitationTypeId);
    return habilitationType ? habilitationType.nom : '';
}
```

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/SuspensionsPersonnelInformations.vue
> +        getSuspensionDate() {
Idem au commentaire précédent.

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/SuspensionsPersonnelInformations.vue
> +        formatSuspensionDate() {
Utiliser les fonctions de date présent dans date.js

2023-09-21 08:36 UTC, Guillaume35 commented on src/views/Suspension.vue
> +        <div class="card bg-custom text-white shadow-lg col-md-12 mt-4">
ici on a des card dans des card dans des card. Pas de modifications obligatoires, mais il doit y avoir moyen de structurer ça d'un manière plus fine, notamment pour que l'affichage sur des petits écrans soit possible.

2023-09-21 16:51 UTC, deathtroll22 commented on src/views/Suspension.vue
> +        <div class="card bg-custom text-white shadow-lg col-md-12 mt-4">
c'est le cas ça fontionne bien sur mobile

2023-09-21 16:53 UTC, deathtroll22 commented on src/views/Suspension.vue
> +.bg-custom {
le 9a est pour ajouter de la transparence :)

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +    <div>
cette div ne sert a rien, on peut la supprimer. Pensez a supprimer la fermeture de la div ligne 33

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +         */
manque le @param pour id dans la déclaration de la method

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +         */
manque le @return de la method `returnNameHab(id)`

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +        * @param {string} date
manque le @return dans la déclaration de la method `chnageFormatDateLit`

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +        changeFormatDateLit(el) {
dans le @param tu nom le parametre `date`, changer donc `el` pour `date`

2023-09-21 18:06 UTC, heligonSeb commented on src/views/SuspensionsPersonnelInformations.vue
> +            return dateFormat(el);
idem changer `el` pour `date`

2023-09-22 16:48 UTC, deathtroll22 commented
normalement tout ce qui a été demandé est pris en compte

2023-09-25 09:14 UTC, Guillaume35 approved these changes

2023-09-25 09:15 UTC, merged