Feat consult collecte
pebble-solutions/App-QSE-habilitation pull request #76
Opened 2023-09-20 14:59 UTC by marilehoux

2023-09-21 08:28 UTC, heligonSeb commented on src/components/HabMonitor.vue
> +						</button>
revoir l'indentation, le `</button>` doit être avancé d'un cran

2023-09-21 08:28 UTC, heligonSeb commented on src/components/HabMonitor.vue
> +// import { RouterLink} from 'vue-router';
supprimer la ligne de commentaire si elle n'est pas utilisé

2023-09-21 08:28 UTC, heligonSeb commented on src/components/LastControlAndResult.vue
> +			if (!this.date) {
revoir l'indentation, il y en a une de trop pour le `if`

2023-09-21 08:28 UTC, heligonSeb commented on src/components/ResultProgressBar.vue
> +    getProgressBarWidth(valueW, valueT) {
revoir l'indentation, la méthode doit être au niveau du commentaire

2023-09-21 08:28 UTC, heligonSeb commented on src/components/StatsQuestionControlleByHabilitation.vue
> +                                <!-- {{ question.question }} -->
supprimer les commentaire inutile

2023-09-21 08:28 UTC, heligonSeb commented on src/components/questions/QuestionItems.vue
> +            <!-- <div v-if="questionStats.personnel.length">
supprimer les commentaires inutiles

2023-09-21 08:28 UTC, heligonSeb commented on src/components/questions/QuestionItems.vue
> +        <!-- composants total des réponses -->
supprimer les commentaires inutiles

2023-09-21 08:28 UTC, heligonSeb commented on src/components/questions/QuestionItems.vue
> +            <div v-else>Pas de Statistiques pour l'agent {{ questionStats.personnel }}</div>
revoir l'indentation d'un cran en arrière

2023-09-21 08:28 UTC, heligonSeb commented on src/components/questions/QuestionStats.vue
> +            <LastControlAndResult v-if="personnelLastResultDate && !textDisplayClass" :date="personnelLastResultDate" :value="personnelLastResult"/>
revoir l'indentation, ajouter un cran a `lastControlAndResult` et a `LastControlAndTextResult`

2023-09-21 08:28 UTC, heligonSeb commented on src/views/HabilitationByAgent.vue
> +    components: {  HabMonitor, Spinner,  SuspensionsPersonnelInformations, RouterView}, //SuspensionsPersonnelInformations  RouterView
supprimer le commentaire a la fin

2023-09-21 08:28 UTC, heligonSeb commented on src/views/PersonnelReadCollecte.vue
> +// import HabMonitorPersonnel from '../components/HabMonitorPersonnel.vue';
supprimer la ligne de commentaire

2023-09-21 08:28 UTC, heligonSeb commented on src/views/PersonnelReadCollecte.vue
> +                // this.setCollecte(data);
supprimer la ligne de commentaire

2023-09-21 08:44 UTC, Guillaume35 requested changes

2023-09-21 08:44 UTC, Guillaume35 commented on src/components/HabMonitor.vue
> +    background-color: #f78c6b9a;
Cette couleur n'existe pas. Remplacer par #f78c6b

2023-09-21 09:54 UTC, marilehoux commented on src/components/HabMonitor.vue
> +						</button>
ok

2023-09-21 09:54 UTC, marilehoux commented on src/components/HabMonitor.vue
> +// import { RouterLink} from 'vue-router';
ok

2023-09-21 09:56 UTC, marilehoux commented on src/components/LastControlAndResult.vue
> +			if (!this.date) {
modifié depuis

2023-09-21 09:57 UTC, marilehoux commented on src/components/ResultProgressBar.vue
> +    getProgressBarWidth(valueW, valueT) {
OK

2023-09-21 09:58 UTC, marilehoux commented on src/components/StatsQuestionControlleByHabilitation.vue
> +                                <!-- {{ question.question }} -->
ok

2023-09-21 10:00 UTC, marilehoux commented on src/components/questions/QuestionItems.vue
> +            <div v-else>Pas de Statistiques pour l'agent {{ questionStats.personnel }}</div>
Ok

2023-09-21 10:01 UTC, marilehoux commented on src/components/questions/QuestionStats.vue
> +            <LastControlAndResult v-if="personnelLastResultDate && !textDisplayClass" :date="personnelLastResultDate" :value="personnelLastResult"/>
ok

2023-09-21 10:02 UTC, marilehoux commented on src/views/HabilitationByAgent.vue
> +    components: {  HabMonitor, Spinner,  SuspensionsPersonnelInformations, RouterView}, //SuspensionsPersonnelInformations  RouterView
ok

2023-09-21 10:24 UTC, marilehoux commented on src/views/PersonnelReadCollecte.vue
> +// import HabMonitorPersonnel from '../components/HabMonitorPersonnel.vue';
ok

2023-09-21 10:25 UTC, marilehoux commented on src/views/PersonnelReadCollecte.vue
> +                // this.setCollecte(data);
OK

2023-09-21 10:26 UTC, marilehoux commented on src/components/HabMonitor.vue
> +    background-color: #f78c6b9a;
ok

2023-09-22 08:53 UTC, Guillaume35 approved these changes

2023-09-22 08:53 UTC, merged